### ISSUE TITLE
Improve model summary

### ISSUE THREAD

**Issue by lgeiger** [plumerai/larq#91]
- Support quantizers not used as a `input_quantizer`
- Support different precisions (e.g. ternary)
- Number of MAC operations
- Memory footprint

**Comment by jamescook106** [comment]
What is wanted in order of priority is:

- [ ] Total memory footprint of the model, and per layer
- [ ] Compression ratio versus Float32 and Float16
- [ ] Support for 8 bit
- [ ] Binary operations and Floating point operations
- [ ] Size of activations
- [ ] Report generator option which is easily readable for post processing
- [ ] Support for 2 bit
- [ ] Support for 4 bit

**Comment by jamescook106** [comment]
@lgeiger anything else?

**Comment by arashb** [comment]
I guess the features requested for model summary are overlapping with the profiler tool I will be working on or we just combine the two tasks?

**Comment by lgeiger** [comment]
Closing in favour of #137
