### ISSUE TITLE
[Question] Any plans to port to PyTorch ?

### ISSUE THREAD

**Issue by vfdev-5** [plumerai/larq#95]
Hi, I was just wondering whether you have some plans to provide a similar library for PyTorch ?
Thanks

**Comment by lgeiger** [comment]
Hey, thanks for reaching out! Unfortunately the short answer is no 😞 

We put quite a bit of thought into the question of which framework we should build Larq on and decided to go with TensorFlow / Keras over PyTorch.. One of our main goals when choosing a high level abstraction was that we don't want to reinvent the wheel by building our own, but rather want to integrate really well into the code people are already using. We really like the Keras API for its simplicity, but it is still very flexible if you want to build complex architectures or custom training loops. Especially with TensorFlow 2.0 on the horizon, we feel that building Larq on tf.keras will allow us to integrate really well into the TensorFlow ecosystem. Especially using https://www.tensorflow.org/datasets/datasets for reproducibility has been really great for us in the past. We plan to release pretrained and finetunable models in the near future and for us that seemed to be a great fit for Keras.

I know everybody prefers a different framework, but for the moment we try to focus on making Larq work really well with the TensorFlow ecosystem and won't try to make it framework agnostic.
Luckily, it's becoming much easier to move between frameworks these days: https://twitter.com/fchollet/status/1052228463300493312 😉 

Larq is currently in its very early stages and we're trying to gather as much feedback from the community as possible. We plan on releasing stable version mid of July. There's a lot of great stuff coming in the next few weeks. What features are you currently missing, or what would help you to adopt Larq for your own work (apart from Larq being written in TensorFlow)?

**Comment by vfdev-5** [comment]
@lgeiger thanks for the answer ! I see your points and I understand the reasoning. 
As far as I understand the features of Larq are those new quantized layers and optimizers which are tested and hopefully will become stable very soon. I thought, maybe, the same work can be rather quickly generalized to pytorch and its ecosystem, to cover other users. 
Anyway, I was also wondering what binarization could perform for semantic segmentation tasks etc.

**Comment by lgeiger** [comment]
Thanks for the comments

> I thought, maybe, the same work can be rather quickly generalized to pytorch and its ecosystem, to cover other users.

I agree, the layers and quantizers can possibly be generalized to pytorch rather quickly. Though our main goal at the moment is to grow the ecosystem around binarized (and extremely quantized) neural networks by also providing pretrained models and "official" implementations of popular papers as well as adding more insights and relevant training metrics. We also plan on developing optimized GPU kernels for faster training. Therefore we are focusing our resources on TensorFlow.

> Anyway, I was also wondering what binarization could perform for semantic segmentation tasks etc.

Oh yes, using binarization for segmentation is an interesting field to explore further
